create table category(
	CATEGORY_CODE VARCHAR2(50)
	CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(100) 
);

INSERT INTO CATEGORY
VALUES('ctg_001', 'SAMSUNG');

INSERT INTO CATEGORY
VALUES('ctg_002', 'LG');

INSERT INTO CATEGORY
VALUES('ctg_003', 'APPLE');

select *
from category;


--카테고리 갯수 쿼리
select nvl(count(*), 0) + 1
from category;


DROP TABLE CATEGORY;